### ISSUE TITLE
circleci tests are broken

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#242]
It has output like the following, but is still considered "successful":
```
case $CIRCLE_NODE_INDEX in 0) npm run testState ;; esac
Your build output is too large to display in the browser. Only the first 400000 characters are displayed.
Download the full output as a file.

> ethereumjs-vm@2.3.2 testState /home/ubuntu/ethereumjs-vm
> node ./tests/tester -s

TAP version 13
# GeneralStateTests
# file: ContractCreationSpam test: ContractCreationSpam
TypeError: Cannot read property 'map' of undefined
    at parseTestCases (/home/ubuntu/ethereumjs-vm/tests/GeneralStateTestsRunner.js:9:47)
    at runStateTest (/home/ubuntu/ethereumjs-vm/tests/GeneralStateTestsRunner.js:119:21)
    at Promise (/home/ubuntu/ethereumjs-vm/tests/tester.js:232:15)
    at Promise (<anonymous>)
    at testing.getTestsFromArgs (/home/ubuntu/ethereumjs-vm/tests/tester.js:220:16)
    at dir.readFiles (/home/ubuntu/ethereumjs-vm/node_modules/ethereumjs-testing/index.js:30:17)
    at /home/ubuntu/ethereumjs-vm/node_modules/node-dir/lib/readfiles.js:110:34
    at tryToString (fs.js:499:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:487:12)
```

**Comment by cdetrio** [comment]
Should be fixed by  https://github.com/ethereumjs/ethereumjs-vm/pull/244
