### ISSUE TITLE
tests fail on 64 bit ubuntu 14.04

### ISSUE THREAD

**Issue by androlo** [ethereumjs/ethereumjs-vm#35]
```
andreas@AndreasLT:~/WebstormProjects/ethereumjs-vm$ npm test

> ethereumjs-vm@1.1.0 test /home/andreas/WebstormProjects/ethereumjs-vm
> ./tests/tester -a

TAP version 13
# executable test
not ok 1  assert.js:89 throw new assert.AssertionError({ ^ 
  ---
    operator: fail
    at: Socket.<anonymous> (/home/andreas/WebstormProjects/ethereumjs-vm/tests/tester.js:11:7)
  ...
not ok 2 AssertionError: false == true at Object.exports.pubToAddress.exports.publicToAddress (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-util/index.js:307:3) at Transaction.getSenderAddress (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-tx/index.js:154:18) at Object.defineProperty.get (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-tx/index.js:97:25) at populateCache (/home/andreas/WebstormProjects/ethereumjs-vm/lib/runTx.js:72:20) at /home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:718:13 at iterate (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:262:13) at async.forEachOfSeries.async.eachOfSeries (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:281:9) at _parallel (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:717:9) at Object.async.series (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:739:9) at VM.module.exports [as runTx] (/home/andreas/WebstormProjects/ethereumjs-vm/lib/runTx.js:39:9) 
  ---
    operator: fail
    at: Socket.<anonymous> (/home/andreas/WebstormProjects/ethereumjs-vm/tests/tester.js:11:7)
  ...
# test the cache api
# should have the correct value in the cache 

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at Object.exports.pubToAddress.exports.publicToAddress (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-util/index.js:307:3)
    at Transaction.getSenderAddress (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-tx/index.js:154:18)
    at Object.defineProperty.get (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/ethereumjs-tx/index.js:97:25)
    at populateCache (/home/andreas/WebstormProjects/ethereumjs-vm/lib/runTx.js:72:20)
    at /home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:718:13
    at iterate (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:281:9)
    at _parallel (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:717:9)
    at Object.async.series (/home/andreas/WebstormProjects/ethereumjs-vm/node_modules/async/lib/async.js:739:9)
    at VM.module.exports [as runTx] (/home/andreas/WebstormProjects/ethereumjs-vm/lib/runTx.js:39:9)
npm ERR! Test failed.  See above for more details.

```

Just pulled repo and ran 'npm install'

**Comment by axic** [comment]
The latest `ethereumjs-util` release should have been a major bump, need to update `ethereumjs-tx` to make tests pass. Will be fixed soon.

**Comment by androlo** [comment]
:+1:

**Comment by androlo** [comment]
I'm sure you know this, but the issue for me is that utils.publicToAddress(key) throws now, unless 'sanitize' is set to 'true'. runTx doesn't set it.

**Comment by axic** [comment]
Yep. Also the git HEAD of -tx uses the pubKey in the proper format without the need for sanitize.

**Comment by axic** [comment]
Fixed by @wanderer removing the ethereumjs-util 2.7.0 release.

**Comment by wanderer** [comment]
sorry my fault! should be fix now.
