### ISSUE TITLE
Error running testVM

### ISSUE THREAD

**Issue by shenghu** [ethereumjs/ethereumjs-vm#513]
`npm run testVM` reports following error

```
ok 41 valid gas usage [file: exp8]
not ok 42 valid gas usage [file: expPowerOf256Of256_0, test: expPowerOf256Of256_0]
  ---
    operator: equal
    expected: '819622'
    actual:   '819262'
    at: replenish (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:1011:17)
  ...
/Users/shenghu/github/ethereumjs-vm/dist/runCode.js:227
          throw e;
          ^

Error: redPow(normalNum)
    at assert (/Users/shenghu/github/ethereumjs-vm/node_modules/bn.js/lib/bn.js:6:21)
    at BN.redPow (/Users/shenghu/github/ethereumjs-vm/node_modules/bn.js/lib/bn.js:2925:5)
    at EXP (/Users/shenghu/github/ethereumjs-vm/dist/evm/opFns.js:179:18)
    at runOp (/Users/shenghu/github/ethereumjs-vm/dist/runCode.js:221:14)
    at /Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:3880:24
    at replenish (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:1011:17)
    at /Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:1041:24)
    at /Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:1046:16
    at _parallel (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:3879:5)
    at Object.series (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:4735:5)
    at iterateVm (/Users/shenghu/github/ethereumjs-vm/dist/runCode.js:154:11)
    at next (/Users/shenghu/github/ethereumjs-vm/node_modules/async/dist/async.js:5223:28)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethereumjs-vm@3.0.0 testVM: `node ./tests/tester -v`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ethereumjs-vm@3.0.0 testVM script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shenghu/.npm/_logs/2019-05-21T02_42_14_007Z-debug.log
```
Is this a real problem, or my env issue?

**Comment by s1na** [comment]
[VMTests](https://ethereum-tests.readthedocs.io/en/latest/test_types/vm_tests.html) only support up to Homestead, and this library supports from Byzantium upwards. Gas rules have changed since Homestead causing the tests to fail. We should eventually drop the `testVM` command, as it's not even being run in CI.

**Comment by shenghu** [comment]
@s1na thanks for reply. it's better to remove this test to avoid confusion.

**Comment by holgerd77** [comment]
@s1na yes, we should definitively do together with some comment on the test runner itself. Could you open a short issue on that (I'm on mobile)?

**Comment by s1na** [comment]
Closing in favor of #520
