### ISSUE TITLE
mainnet block 0x01331e causes stateTrie crash

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-vm#61]
```
/Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:359
  var lastNode = stack.pop()
                      ^

TypeError: Cannot read property 'pop' of undefined
    at SecureTrie.Trie._updateNode (/Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:359:23)
    at /Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:106:16
    at /Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:442:14
    at processNode (/Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:447:23)
    at /Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:438:5
    at /Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/baseTrie.js:179:7
    at /Users/kumavis/dev/node-blockchain-server/node_modules/merkle-patricia-tree/util.js:75:7
    at /Users/kumavis/dev/node-blockchain-server/node_modules/async/lib/async.js:52:16
    at /Users/kumavis/dev/node-blockchain-server/node_modules/async/lib/async.js:269:32
    at /Users/kumavis/dev/node-blockchain-server/node_modules/async/lib/async.js:44:16
```

**Comment by axic** [comment]
Is this still the case?

**Comment by kumavis** [comment]
This is no longer a problem
