### ISSUE TITLE
fullexample.js: self._trie.get is not a function

### ISSUE THREAD

**Issue by jeremyellis** [ethereumjs/ethereumjs-vm#85]
Just trying to run fullexample.js, getting `self._trie.get is not a function`.

Full stack trace: 

```
TypeError: self._trie.get is not a function
    at Cache._lookupAccount (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/lib/cache.js:41:14)
    at /home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/lib/cache.js:74:10
    at /home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:181:20
    at iterate (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:214:22)
    at Cache.warm (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/lib/cache.js:72:9)
    at StateManager.proto.warmCache (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/lib/stateManager.js:260:14)
    at populateCache (/home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/lib/runTx.js:85:23)
    at /home/jeremy/Development/vm-test/node_modules/ethereumjs-vm/node_modules/async/lib/async.js:718:13

```

I have these dependencies in my package.json

```
  "dependencies": {
    "async": "^2.0.1",
    "ethereumjs-account": "^2.0.4",
    "ethereumjs-tx": "^1.1.2",
    "ethereumjs-util": "^4.5.0",
    "ethereumjs-vm": "^1.4.1",
    "merkle-patricia-tree": "^2.1.2",
    "rlp": "^2.0.0"
  }
```

using 

```
node v6.5.0
npm 3.10.6
```

**Comment by jeremyellis** [comment]
I believe fullexample.js was broken in [this commit](https://github.com/ethereumjs/ethereumjs-vm/commit/7d3f0b8fc7899d94678c330e6587c6ae2dcc9b16)

Specifically this diff:
```
-var vm = new VM(stateTrie)
+var vm = new VM({state: stateTrie})
```

using `var vm = new VM(stateTrie)` instead of `new VM({state: stateTrie})` fixes the issue.

**Comment by wanderer** [comment]
should be fixed now.
